"""
Algorithm #2 Phase 5. Semantic forest-health keep/drop masks with optional Sentinel-1 descriptor summaries.

This version consumes the Phase 3 preprocessing cache generated by:
    preprocess_sdv_sentinel2_shared_cache_phase3.py

It no longer reopens Sentinel-2 ZIP scenes, recomputes spectral indices, decodes SCL,
or rasterizes FMU polygons per scene. It reuses:
- scene_inventory.csv
- clear_masks/*.tif
- index_stacks/*.tif
- all_fmu_group_id.tif
- group_lut_all_fmu.csv

The empirical envelope ZIP remains the Algorithm #1 output bundle.
"""
from __future__ import annotations

import io
import zipfile
from pathlib import Path
from typing import Dict, List, Tuple, Set
import time

import numpy as np
import pandas as pd

from sdv_shared import (
    doy_bin_label,
    doy_bin_center_from_label,
    read_uint8_mask,
    read_int_raster,
    read_float32_stack,
    same_grid,
    write_uint8_mask,
    write_int16,
    write_float32,
    read_json,
    S1_DESCRIPTOR_BANDS,
    load_s1_inventory,
    find_nearest_s1_scene,
    summarize_stack_on_mask,
)

# =============================================================================
# HARD-CODED CONFIG
# =============================================================================

ENVELOPE_RUN = "blacklist_and_caution"
ENVELOPE_OUTPUT_ROOT = Path("D:/Forest_Disturbance/outputs")
ENVELOPE_RUN_DIRNAME = f"sdv_si_empirical_envelopes_per_compositional_group_{ENVELOPE_RUN}"
ENVELOPE_SOURCE = ENVELOPE_OUTPUT_ROOT / f"{ENVELOPE_RUN_DIRNAME}.zip"
ENVELOPE_CSV_IN_ZIP = f"{ENVELOPE_RUN_DIRNAME}/doy_bin_envelopes.csv"
SCENE_RECOMMENDATION_CSV_IN_ZIP = f"{ENVELOPE_RUN_DIRNAME}/scene_blacklist_recommendation.csv"

CACHE_ROOT = Path("D:/Forest_Disturbance/outputs/sdv_phase3_preprocessing_cache")
S1_CACHE_ROOT = Path("D:/Forest_Disturbance/outputs/sdv_phase5_sentinel1_descriptor_cache")

FILTER_TARGET_SCENES_TO_ENVELOPE_POLICY = True
EXCLUDE_SCENES_WITHOUT_RECOMMENDATION = True
DEDUPLICATE_TARGET_SCENES_BY_DATE = True

USE_ALL_FOREST_FALLBACK_FOR_UNKNOWN = True
ALL_FOREST_FALLBACK_CODE = "ALL_FOREST"
ALL_FOREST_FALLBACK_LABEL = "All forest fallback"

DOY_BIN_WIDTH = 30
CORE_INDICES = ["NDVI", "NDMI", "NBR"]
OPTIONAL_INDICES = ["NDRE"]
ALL_INDEX_STACK_BANDS = ["NDVI", "NDMI", "NBR", "NDRE", "NDSI"]
KEEP_VOTES_REQUIRED = 2

ENVELOPE_LOW_COL = "median_of_date_q10"
ENVELOPE_HIGH_COL = "median_of_date_q90"
USE_NEAREST_BIN_FALLBACK = False

WRITE_INDEX_INSIDE_MASKS = False
OUTPUT_DIR = Path(f"D:/Forest_Disturbance/outputs/semantic_masks_s1s2_empirical_envelopes_{ENVELOPE_RUN}_eligible")
VERBOSE = True

# Phase 4 diagnostic outputs. These do not modify the default keep/drop vote.
WRITE_ANOMALY_SCORE = True
ANOMALY_SCORE_NODATA = -9999.0
ANOMALY_EPS = 1.0e-6
WRITE_ENVELOPE_CONFIDENCE_MASK = True
ENVELOPE_CONFIDENCE_VALUES = {"high": 1, "medium": 2, "low": 3, "missing": 4, "unknown": 4}

# Used only when an older envelope table has no Phase 4 confidence columns.
ENVELOPE_CONFIDENCE_HIGH_MIN_UNIQUE_DATES = 5
ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES = 3
MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE = 1000

# Phase 5 Sentinel-1 descriptor summaries. These descriptors are diagnostic and
# do not change the default optical keep/drop vote.
ENABLE_S1_DESCRIPTOR_SUMMARIES = True
S1_MAX_ABS_DATE_OFFSET_DAYS = 45
# Use "auto" to report only S1 descriptors that exist in the nearest-date
# cache scene. This avoids all-nodata VV summary columns when the S1 ZIPs
# contain VH only.
S1_DESCRIPTORS_TO_SUMMARIZE = "auto"
S1_DESCRIPTOR_EXCLUDE_FROM_SUMMARY = {"S1_VALID"}

# =============================================================================
# Helpers
# =============================================================================


def log(msg: str) -> None:
    if VERBOSE:
        print(msg, flush=True)


def require_cache_file(path: Path) -> Path:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Required Phase 3 cache file is missing: {path}\n"
            "Run preprocess_sdv_sentinel2_shared_cache_phase3.py before Algorithm #2 Phase 4."
        )
    return path


def _as_bool(value) -> bool:
    if isinstance(value, (bool, np.bool_)):
        return bool(value)
    if pd.isna(value):
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def classify_envelope_confidence_from_values(n_unique_dates, support_pixels_total) -> dict:
    """Classify support when an older envelope table lacks confidence fields."""
    try:
        n_unique_dates = int(n_unique_dates)
    except Exception:
        n_unique_dates = 0
    try:
        support_pixels_total = int(support_pixels_total)
    except Exception:
        support_pixels_total = 0

    if n_unique_dates <= 0 or support_pixels_total <= 0:
        code = 4
        label = "missing"
    elif n_unique_dates >= ENVELOPE_CONFIDENCE_HIGH_MIN_UNIQUE_DATES:
        code = 1
        label = "high"
    elif (
        n_unique_dates >= ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES
        and support_pixels_total >= MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE
    ):
        code = 2
        label = "medium"
    else:
        code = 3
        label = "low"

    low_temporal = n_unique_dates < ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES
    low_pixel = support_pixels_total < MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE
    reasons = []
    if low_temporal:
        reasons.append(f"unique_dates<{ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES}")
    if low_pixel:
        reasons.append(f"support_pixels_total<{MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE}")
    if not reasons:
        reasons.append("sufficient_support")
    return {
        "envelope_confidence": label,
        "envelope_confidence_code": code,
        "low_support_flag": bool(label in {"low", "missing"}),
        "low_temporal_support_flag": bool(low_temporal),
        "support_pixels_total_low_flag": bool(low_pixel),
        "confidence_reason": ";".join(reasons),
    }


def ensure_envelope_confidence_columns(env: pd.DataFrame) -> pd.DataFrame:
    """Ensure Phase 4 confidence columns exist for both new and older envelope tables."""
    env = env.copy()
    if "n_unique_dates" not in env.columns:
        env["n_unique_dates"] = env.get("n_dates", np.nan)
    if "n_scene_records" not in env.columns:
        env["n_scene_records"] = env.get("n_dates", np.nan)
    if "operational_width" not in env.columns and {ENVELOPE_LOW_COL, ENVELOPE_HIGH_COL}.issubset(env.columns):
        env["operational_width"] = pd.to_numeric(env[ENVELOPE_HIGH_COL], errors="coerce") - pd.to_numeric(env[ENVELOPE_LOW_COL], errors="coerce")

    metas = [
        classify_envelope_confidence_from_values(row.get("n_unique_dates", row.get("n_dates", np.nan)), row.get("support_pixels_total", np.nan))
        for _, row in env.iterrows()
    ]
    for col in [
        "envelope_confidence",
        "envelope_confidence_code",
        "low_support_flag",
        "low_temporal_support_flag",
        "support_pixels_total_low_flag",
        "confidence_reason",
    ]:
        if col not in env.columns:
            env[col] = [m[col] for m in metas]
        else:
            missing = env[col].isna() | env[col].astype(str).str.strip().isin(["", "nan", "None"])
            if missing.any():
                fill_values = pd.Series([m[col] for m in metas], index=env.index)
                env.loc[missing, col] = fill_values.loc[missing]
    return env


def confidence_from_row(row: pd.Series) -> str:
    value = str(row.get("envelope_confidence", "unknown")).strip().lower()
    if value in ENVELOPE_CONFIDENCE_VALUES:
        return value
    meta = classify_envelope_confidence_from_values(row.get("n_unique_dates", row.get("n_dates", np.nan)), row.get("support_pixels_total", np.nan))
    return str(meta["envelope_confidence"])


def confidence_code_from_row(row: pd.Series) -> int:
    try:
        code = int(row.get("envelope_confidence_code"))
        if code in {1, 2, 3, 4}:
            return code
    except Exception:
        pass
    return ENVELOPE_CONFIDENCE_VALUES.get(confidence_from_row(row), ENVELOPE_CONFIDENCE_VALUES["unknown"])


def worst_confidence(confidences: List[str]) -> str:
    """Return the weakest confidence label, where low/missing is weaker than medium/high."""
    if not confidences:
        return "unknown"
    severity = {"high": 1, "medium": 2, "low": 3, "missing": 4, "unknown": 4}
    inv = {1: "high", 2: "medium", 3: "low", 4: "unknown"}
    return inv.get(max(severity.get(str(c).lower(), 4) for c in confidences), "unknown")


def _row_value(row: pd.Series, col: str, default=np.nan):
    return row[col] if col in row.index else default


def load_envelopes() -> pd.DataFrame:
    if ENVELOPE_SOURCE.suffix.lower() == ".zip":
        with zipfile.ZipFile(ENVELOPE_SOURCE, "r") as zf:
            with zf.open(ENVELOPE_CSV_IN_ZIP) as f:
                env = pd.read_csv(io.BytesIO(f.read()))
    else:
        env = pd.read_csv(ENVELOPE_SOURCE)

    if "doy_bin_center" not in env.columns:
        env["doy_bin_center"] = env["doy_bin_label"].apply(doy_bin_center_from_label)

    env = ensure_envelope_confidence_columns(env)

    if USE_ALL_FOREST_FALLBACK_FOR_UNKNOWN and ALL_FOREST_FALLBACK_CODE not in set(env["group_code"].astype(str)):
        num_cols = [c for c in env.columns if c not in {"group_code", "group_label", "index", "doy_bin_label"}]
        agg = {c: "median" for c in num_cols if pd.api.types.is_numeric_dtype(env[c])}
        af = env.groupby(["index", "doy_bin_label"], as_index=False).agg(agg)
        af["group_code"] = ALL_FOREST_FALLBACK_CODE
        af["group_label"] = ALL_FOREST_FALLBACK_LABEL
        if "doy_bin_center" not in af.columns:
            af["doy_bin_center"] = af["doy_bin_label"].apply(doy_bin_center_from_label)
        af = ensure_envelope_confidence_columns(af)
        af = af.reindex(columns=env.columns)
        env = pd.concat([env, af], ignore_index=True)
    return ensure_envelope_confidence_columns(env)


def allowed_recommendations_for_envelope_run(run: str) -> Set[str]:
    run = run.lower().strip()
    if run == "none":
        return {"keep", "caution", "blacklist"}
    if run == "blacklist":
        return {"keep", "caution"}
    if run == "blacklist_and_caution":
        return {"keep"}
    raise ValueError(f"Unsupported ENVELOPE_RUN: {run!r}")


def load_scene_recommendations() -> pd.DataFrame:
    if ENVELOPE_SOURCE.suffix.lower() == ".zip":
        with zipfile.ZipFile(ENVELOPE_SOURCE, "r") as zf:
            with zf.open(SCENE_RECOMMENDATION_CSV_IN_ZIP) as f:
                rec = pd.read_csv(io.BytesIO(f.read()))
    else:
        source_path = Path(ENVELOPE_SOURCE)
        if source_path.is_dir():
            rec_path = source_path / "scene_blacklist_recommendation.csv"
        else:
            rec_path = source_path.parent / "scene_blacklist_recommendation.csv"
        rec = pd.read_csv(rec_path)
    if "scene" not in rec.columns or "recommendation" not in rec.columns:
        raise ValueError("scene_blacklist_recommendation.csv must contain 'scene' and 'recommendation' columns")
    rec = rec.copy()
    rec["scene"] = rec["scene"].astype(str)
    rec["recommendation"] = rec["recommendation"].astype(str).str.lower().str.strip()
    return rec


def load_scene_inventory_with_recommendations() -> pd.DataFrame:
    """Load cache inventory and attach recommendations from the Algorithm #1 envelope bundle.

    The envelope bundle is treated as the source of truth for scene eligibility.
    Cache-side recommendation columns are retained with a ``cache_`` prefix when
    they differ from the bundle columns.
    """
    inv = pd.read_csv(require_cache_file(CACHE_ROOT / "scene_inventory.csv"))
    inv["scene"] = inv["scene"].astype(str)
    rec = load_scene_recommendations()

    for col in ["recommendation", "recommendation_reason"]:
        if col in inv.columns:
            inv = inv.rename(columns={col: f"cache_{col}"})

    rec_cols = [c for c in ["scene", "recommendation", "recommendation_reason", "clear_frac", "veg_frac", "cloud_frac", "snow_frac", "shadow_frac", "scl7_frac"] if c in rec.columns]
    merged = inv.merge(rec[rec_cols], on="scene", how="left", suffixes=("", "_rec"))
    if "recommendation" not in merged.columns:
        merged["recommendation"] = merged.get("cache_recommendation", "missing")
    if "recommendation_reason" not in merged.columns:
        merged["recommendation_reason"] = merged.get("cache_recommendation_reason", "")
    merged["recommendation"] = merged["recommendation"].astype(str).str.lower().str.strip()
    return merged


def filename_quality_score(scene_name: str) -> float:
    s = str(scene_name).lower()
    score = 0.0
    if "no_cloud" in s or "no-cloud" in s or "nocloud" in s:
        score += 100.0
    if "verylow" in s or "very_low" in s:
        score += 50.0
    if "low_cloud" in s or "low-cloud" in s or "lowcloud" in s:
        score += 20.0
    if "lowmedium" in s or "medium" in s:
        score -= 20.0
    if "high_cloud" in s or "high-cloud" in s or "highcloud" in s:
        score -= 80.0
    if "snow" in s or "winter" in s:
        score -= 100.0
    return score


def filter_inventory_by_recommendation(inv: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    if not FILTER_TARGET_SCENES_TO_ENVELOPE_POLICY:
        out = inv.copy()
        out["included_by_recommendation"] = True
        out["allowed_recommendations"] = "filter disabled"
        out["filter_policy"] = ENVELOPE_RUN
        out["filter_reason"] = "scene filtering disabled"
        return out, out.copy()

    allowed = allowed_recommendations_for_envelope_run(ENVELOPE_RUN)
    log_rows = []
    included_flags = []
    for row in inv.itertuples(index=False):
        rec = str(getattr(row, "recommendation", "missing")).lower().strip()
        if rec in {"", "nan", "none"}:
            rec = "missing"
        if rec == "missing":
            include = not EXCLUDE_SCENES_WITHOUT_RECOMMENDATION
            reason = "not found in scene_blacklist_recommendation.csv"
        else:
            include = rec in allowed
            reason = str(getattr(row, "recommendation_reason", ""))
        included_flags.append(include)
        log_rows.append({
            "scene": row.scene,
            "scene_key": getattr(row, "scene_key", ""),
            "date": getattr(row, "date", ""),
            "recommendation": rec,
            "included_by_recommendation": include,
            "allowed_recommendations": ";".join(sorted(allowed)),
            "filter_policy": ENVELOPE_RUN,
            "filter_reason": reason,
            "clear_frac": getattr(row, "clear_frac", np.nan) if hasattr(row, "clear_frac") else np.nan,
            "scl_available": getattr(row, "scl_available", np.nan) if hasattr(row, "scl_available") else np.nan,
            "scl_used": getattr(row, "scl_used", np.nan) if hasattr(row, "scl_used") else np.nan,
        })
    eligibility = pd.DataFrame(log_rows)
    out = inv.loc[included_flags].copy().reset_index(drop=True)
    return out, eligibility


def deduplicate_inventory_by_date(inv: pd.DataFrame, eligibility: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    eligibility = eligibility.copy()
    eligibility["included_after_date_dedup"] = eligibility["included_by_recommendation"].astype(bool)
    eligibility["duplicate_date_selected"] = False
    if not DEDUPLICATE_TARGET_SCENES_BY_DATE or inv.empty:
        eligibility["included"] = eligibility["included_after_date_dedup"]
        return inv, eligibility

    kept_rows = []
    for date, sub in inv.groupby("date", dropna=False):
        if len(sub) == 1:
            chosen = sub.iloc[0]
        else:
            temp = sub.copy()
            for col in ["clear_frac", "veg_frac", "cloud_frac", "snow_frac", "shadow_frac", "scl7_frac"]:
                if col not in temp.columns:
                    temp[col] = np.nan
            temp["filename_quality_score"] = temp["scene"].map(filename_quality_score)
            temp["_clear_sort"] = pd.to_numeric(temp["clear_frac"], errors="coerce").fillna(-1.0)
            temp["_veg_sort"] = pd.to_numeric(temp["veg_frac"], errors="coerce").fillna(-1.0)
            temp["_cloud_sort"] = pd.to_numeric(temp["cloud_frac"], errors="coerce").fillna(1.0)
            temp["_snow_sort"] = pd.to_numeric(temp["snow_frac"], errors="coerce").fillna(1.0)
            temp = temp.sort_values(
                ["filename_quality_score", "_clear_sort", "_veg_sort", "_cloud_sort", "_snow_sort", "scene"],
                ascending=[False, False, False, True, True, True],
            )
            chosen = temp.iloc[0]
        kept_rows.append(chosen)

        date_mask = eligibility["date"].astype(str).eq(str(date)) & eligibility["included_by_recommendation"].astype(bool)
        chosen_mask = eligibility["scene"].astype(str).eq(str(chosen["scene"]))
        eligibility.loc[date_mask, "included_after_date_dedup"] = False
        eligibility.loc[chosen_mask, "included_after_date_dedup"] = True
        eligibility.loc[chosen_mask, "duplicate_date_selected"] = True
        dropped_mask = date_mask & (~chosen_mask)
        if dropped_mask.any():
            eligibility.loc[dropped_mask, "filter_reason"] = (
                eligibility.loc[dropped_mask, "filter_reason"].astype(str)
                + f"; duplicate acquisition date {date}; selected {chosen['scene']}"
            )

    kept = pd.DataFrame(kept_rows).sort_values(["date", "scene"]).reset_index(drop=True)
    eligibility["included"] = eligibility["included_after_date_dedup"]
    return kept, eligibility


def build_envelope_lookup(env: pd.DataFrame) -> Dict[Tuple[str, str, str], pd.Series]:
    return {
        (str(row["group_code"]), str(row["index"]), str(row["doy_bin_label"])): row
        for _, row in env.iterrows()
    }


def lookup_envelope_rows(
    env: pd.DataFrame,
    env_lookup: Dict[Tuple[str, str, str], pd.Series],
    group_code: str,
    target_bin_label: str,
    indices: List[str],
) -> Tuple[Dict[str, pd.Series], List[dict]]:
    out: Dict[str, pd.Series] = {}
    logs: List[dict] = []
    group_env = env[env["group_code"] == group_code]
    target_center = doy_bin_center_from_label(target_bin_label)
    for idx in indices:
        exact_key = (str(group_code), str(idx), str(target_bin_label))
        row = env_lookup.get(exact_key)
        if row is not None:
            out[idx] = row
            logs.append({
                "group_code": group_code,
                "index": idx,
                "requested_bin": target_bin_label,
                "used_bin": row["doy_bin_label"],
                "fallback_used": False,
            })
            continue
        subset = group_env[group_env["index"] == idx]
        if USE_NEAREST_BIN_FALLBACK and len(subset) > 0:
            temp = subset.copy()
            temp["bin_distance"] = (temp["doy_bin_center"] - target_center).abs()
            row = temp.sort_values(["bin_distance", "n_dates", "support_pixels_total"], ascending=[True, False, False]).iloc[0]
            out[idx] = row
            logs.append({
                "group_code": group_code,
                "index": idx,
                "requested_bin": target_bin_label,
                "used_bin": row["doy_bin_label"],
                "fallback_used": True,
            })
        else:
            raise KeyError(f"No envelope found for group={group_code}, index={idx}, bin={target_bin_label}")
    return out, logs



_S1_INVENTORY_CACHE: pd.DataFrame | None = None


def get_s1_inventory_cached() -> pd.DataFrame:
    global _S1_INVENTORY_CACHE
    if _S1_INVENTORY_CACHE is None:
        _S1_INVENTORY_CACHE = load_s1_inventory(S1_CACHE_ROOT)
    return _S1_INVENTORY_CACHE


def resolve_s1_descriptors_to_summarize(s1_row: pd.Series, s1_stack: Dict[str, np.ndarray]) -> List[str]:
    cfg = S1_DESCRIPTORS_TO_SUMMARIZE
    if isinstance(cfg, str) and cfg.lower().strip() == "auto":
        found = []
        txt = str(s1_row.get("descriptor_bands_available", ""))
        for name in [x.strip() for x in txt.split(",") if x.strip()]:
            if name not in found and name not in S1_DESCRIPTOR_EXCLUDE_FROM_SUMMARY:
                found.append(name)
        if not found:
            for name, arr in s1_stack.items():
                if name in S1_DESCRIPTOR_EXCLUDE_FROM_SUMMARY:
                    continue
                if arr is not None and np.isfinite(arr).any():
                    found.append(name)
        return found
    return [str(x) for x in cfg if str(x) not in S1_DESCRIPTOR_EXCLUDE_FROM_SUMMARY]


def summarize_nearest_s1_for_scene(
    scene_date: pd.Timestamp,
    semantic_domain: np.ndarray,
    group_raster: np.ndarray,
    group_lut_records: Dict[int, dict],
    group_profile: dict,
    out_scene_dir: Path,
) -> Tuple[dict, pd.DataFrame]:
    """Summarize nearest-date Sentinel-1 descriptors over the Algorithm #2 domain."""
    meta = {
        "s1_descriptor_summary_enabled": bool(ENABLE_S1_DESCRIPTOR_SUMMARIES),
        "s1_scene_used": "",
        "s1_date_used": "",
        "s1_abs_offset_days": np.nan,
        "s1_descriptor_stack_path": "",
        "s1_descriptor_available": False,
    }
    if not ENABLE_S1_DESCRIPTOR_SUMMARIES:
        return meta, pd.DataFrame()
    inv = get_s1_inventory_cached()
    if inv.empty:
        return meta, pd.DataFrame()
    s1_row = find_nearest_s1_scene(inv, scene_date, S1_MAX_ABS_DATE_OFFSET_DAYS)
    if s1_row is None:
        return meta, pd.DataFrame()
    stack_path = Path(str(s1_row.get("s1_stack_path", "")))
    valid_path = Path(str(s1_row.get("s1_valid_mask_path", "")))
    if not stack_path.exists() or not valid_path.exists():
        return meta, pd.DataFrame()
    try:
        s1_stack, s1_profile = read_float32_stack(stack_path, expected_names=S1_DESCRIPTOR_BANDS)
    except Exception:
        s1_stack, s1_profile = read_float32_stack(stack_path)
    s1_descriptors_to_summarize = resolve_s1_descriptors_to_summarize(s1_row, s1_stack)
    s1_valid_arr, s1_valid_profile = read_uint8_mask(valid_path)
    if not same_grid(s1_profile, group_profile) or not same_grid(s1_valid_profile, group_profile):
        raise RuntimeError(f"Sentinel-1 descriptor grid does not match semantic-mask grid: {stack_path}")
    s1_valid = s1_valid_arr == 1
    rows = []
    for gid, info in group_lut_records.items():
        mask_g = semantic_domain & (group_raster == int(gid)) & s1_valid
        if not np.any(mask_g):
            continue
        row = {
            "group_id": int(gid),
            "group_code": info.get("group_code", ""),
            "group_label": info.get("group_label", ""),
            "semantic_domain_s1_valid_px": int(mask_g.sum()),
        }
        row.update(summarize_stack_on_mask(s1_stack, mask_g, s1_descriptors_to_summarize))
        rows.append(row)
    out_df = pd.DataFrame(rows)
    if not out_df.empty:
        out_df.insert(0, "s1_abs_offset_days", int(s1_row.get("abs_offset_days", abs((pd.Timestamp(s1_row['date']) - scene_date).days))))
        out_df.insert(0, "s1_date", pd.Timestamp(s1_row["date"]).date().isoformat())
        out_df.insert(0, "s1_scene", str(s1_row["scene"]))
        out_df.to_csv(out_scene_dir / "s1_scene_descriptor_summary.csv", index=False)
    meta.update({
        "s1_scene_used": str(s1_row.get("scene", "")),
        "s1_date_used": pd.Timestamp(s1_row["date"]).date().isoformat(),
        "s1_abs_offset_days": int(s1_row.get("abs_offset_days", abs((pd.Timestamp(s1_row['date']) - scene_date).days))),
        "s1_descriptor_stack_path": str(stack_path),
        "s1_descriptor_available": True,
        "s1_descriptors_summarized": ",".join(s1_descriptors_to_summarize),
    })
    return meta, out_df


def process_cached_scene(
    scene_row: pd.Series,
    env: pd.DataFrame,
    env_lookup: Dict[Tuple[str, str, str], pd.Series],
    group_raster: np.ndarray,
    group_profile: dict,
    group_lut: pd.DataFrame,
) -> Tuple[dict, pd.DataFrame, pd.DataFrame]:
    scene = str(scene_row["scene"])
    scene_key = str(scene_row.get("scene_key", scene_row.get("scene_stem", scene)))
    scene_date = pd.Timestamp(scene_row["date"])
    scene_doy = int(scene_row["doy"])
    bin_label = doy_bin_label(scene_doy, DOY_BIN_WIDTH)

    clear_arr, clear_profile = read_uint8_mask(require_cache_file(Path(scene_row["clear_mask_path"])))
    if not same_grid(clear_profile, group_profile):
        raise RuntimeError(f"Clear mask grid does not match all-FMU group raster for {scene}")
    idx, idx_profile = read_float32_stack(require_cache_file(Path(scene_row["index_stack_path"])), expected_names=ALL_INDEX_STACK_BANDS)
    if not same_grid(idx_profile, group_profile):
        raise RuntimeError(f"Index stack grid does not match all-FMU group raster for {scene}")

    all_used_indices = CORE_INDICES + [x for x in OPTIONAL_INDICES if x not in CORE_INDICES]
    inside_by_index = {name: np.zeros(group_raster.shape, dtype=bool) for name in all_used_indices}
    vote_count = np.zeros(group_raster.shape, dtype=np.uint8)
    anomaly_sum = np.zeros(group_raster.shape, dtype=np.float32)
    anomaly_count = np.zeros(group_raster.shape, dtype=np.uint8)
    confidence_code_raw = np.full(group_raster.shape, 255, dtype=np.uint8)
    group_confidence_meta: Dict[int, dict] = {}
    clear_mask = clear_arr == 1
    grouped_valid = clear_mask & (group_raster > 0)

    group_lut_records = {
        int(r.group_id): {"group_code": r.group_code, "group_label": r.group_label}
        for r in group_lut[["group_id", "group_code", "group_label"]].itertuples(index=False)
    }

    lookup_logs: List[dict] = []
    for gid, meta in group_lut_records.items():
        group_code = meta["group_code"]
        mask_g = grouped_valid & (group_raster == gid)
        if not np.any(mask_g):
            continue
        rows_by_index, logs = lookup_envelope_rows(env, env_lookup, group_code, bin_label, all_used_indices)
        lookup_logs.extend(logs)

        core_confidences = [confidence_from_row(rows_by_index[name]) for name in CORE_INDICES]
        core_confidence = worst_confidence(core_confidences)
        group_confidence_meta[int(gid)] = {
            "core_envelope_confidence": core_confidence,
            "core_envelope_confidence_code": ENVELOPE_CONFIDENCE_VALUES.get(core_confidence, ENVELOPE_CONFIDENCE_VALUES["unknown"]),
            "core_low_confidence_lookup_count": int(sum(c == "low" for c in core_confidences)),
            "core_medium_confidence_lookup_count": int(sum(c == "medium" for c in core_confidences)),
            "core_high_confidence_lookup_count": int(sum(c == "high" for c in core_confidences)),
            "core_missing_or_unknown_confidence_lookup_count": int(sum(c in {"missing", "unknown"} for c in core_confidences)),
        }
        confidence_code_raw[mask_g] = np.uint8(ENVELOPE_CONFIDENCE_VALUES.get(core_confidence, ENVELOPE_CONFIDENCE_VALUES["unknown"]))

        for name in all_used_indices:
            low = float(rows_by_index[name][ENVELOPE_LOW_COL])
            high = float(rows_by_index[name][ENVELOPE_HIGH_COL])
            arr = idx[name]
            finite = mask_g & np.isfinite(arr)
            ok = finite & (arr >= low) & (arr <= high)
            inside_by_index[name][ok] = True

            if WRITE_ANOMALY_SCORE and name in CORE_INDICES:
                width = max(float(high - low), ANOMALY_EPS)
                dist = np.zeros(arr.shape, dtype=np.float32)
                below = finite & (arr < low)
                above = finite & (arr > high)
                dist[below] = ((low - arr[below]) / width).astype(np.float32)
                dist[above] = ((arr[above] - high) / width).astype(np.float32)
                anomaly_sum[finite] += dist[finite]
                anomaly_count[finite] += 1

    for name in CORE_INDICES:
        vote_count = vote_count + inside_by_index[name].astype(np.uint8)

    finite_core = np.ones(group_raster.shape, dtype=bool)
    for name in CORE_INDICES:
        finite_core &= np.isfinite(idx[name])
    semantic_domain = grouped_valid & finite_core

    keep = semantic_domain & (vote_count >= KEEP_VOTES_REQUIRED)
    drop = semantic_domain & (~keep)

    if DEDUPLICATE_TARGET_SCENES_BY_DATE:
        out_scene_dir = OUTPUT_DIR / scene_date.strftime("%Y-%m-%d")
    else:
        out_scene_dir = OUTPUT_DIR / scene_key
    out_scene_dir.mkdir(parents=True, exist_ok=True)

    # Sentinel-1 summaries are computed later after the semantic domain is known.

    keep_u8 = np.full(group_raster.shape, 255, dtype=np.uint8)
    keep_u8[semantic_domain] = 0
    keep_u8[keep] = 1
    write_uint8_mask(out_scene_dir / "semantic_keep_mask.tif", keep_u8, group_profile)

    drop_u8 = np.full(group_raster.shape, 255, dtype=np.uint8)
    drop_u8[semantic_domain] = 0
    drop_u8[drop] = 1
    write_uint8_mask(out_scene_dir / "semantic_drop_mask.tif", drop_u8, group_profile)

    votes_u8 = np.full(group_raster.shape, 255, dtype=np.uint8)
    votes_u8[semantic_domain] = vote_count[semantic_domain]
    write_uint8_mask(out_scene_dir / "semantic_vote_count.tif", votes_u8, group_profile)

    write_int16(out_scene_dir / "semantic_group_id.tif", group_raster.astype(np.int16), group_profile, nodata=-32768)

    anomaly_score = None
    if WRITE_ANOMALY_SCORE:
        anomaly_score = np.full(group_raster.shape, ANOMALY_SCORE_NODATA, dtype=np.float32)
        valid_anom = semantic_domain & (anomaly_count > 0)
        anomaly_score[valid_anom] = anomaly_sum[valid_anom] / anomaly_count[valid_anom].astype(np.float32)
        write_float32(out_scene_dir / "semantic_anomaly_score.tif", anomaly_score, group_profile, nodata=ANOMALY_SCORE_NODATA)

    if WRITE_ENVELOPE_CONFIDENCE_MASK:
        confidence_u8 = np.full(group_raster.shape, 255, dtype=np.uint8)
        confidence_u8[semantic_domain] = confidence_code_raw[semantic_domain]
        write_uint8_mask(out_scene_dir / "semantic_envelope_confidence.tif", confidence_u8, group_profile)

    if WRITE_INDEX_INSIDE_MASKS:
        for name in all_used_indices:
            arr = np.full(group_raster.shape, 255, dtype=np.uint8)
            arr[semantic_domain] = 0
            arr[inside_by_index[name] & semantic_domain] = 1
            write_uint8_mask(out_scene_dir / f"inside_{name.lower()}_envelope.tif", arr, group_profile)

    group_rows = []
    for gid, meta in group_lut_records.items():
        mask_g = semantic_domain & (group_raster == gid)
        if not np.any(mask_g):
            continue
        keep_g = keep & (group_raster == gid)
        drop_g = drop & (group_raster == gid)
        row = {
            "scene": scene,
            "scene_key": scene_key,
            "date": scene_date.date().isoformat(),
            "doy": scene_doy,
            "doy_bin_label": bin_label,
            "group_id": gid,
            "group_code": meta["group_code"],
            "group_label": meta["group_label"],
            "semantic_domain_px": int(mask_g.sum()),
            "keep_px": int(keep_g.sum()),
            "drop_px": int(drop_g.sum()),
            "keep_pct": float(100.0 * keep_g.sum() / mask_g.sum()),
            "mean_vote_count": float(vote_count[mask_g].mean()),
            **group_confidence_meta.get(int(gid), {
                "core_envelope_confidence": "unknown",
                "core_envelope_confidence_code": ENVELOPE_CONFIDENCE_VALUES["unknown"],
                "core_low_confidence_lookup_count": 0,
                "core_medium_confidence_lookup_count": 0,
                "core_high_confidence_lookup_count": 0,
                "core_missing_or_unknown_confidence_lookup_count": len(CORE_INDICES),
            }),
        }
        if anomaly_score is not None:
            row["mean_anomaly_score"] = float(np.nanmean(np.where(mask_g, anomaly_score, np.nan)))
        for name in all_used_indices:
            row[f"inside_{name.lower()}_pct"] = float(100.0 * inside_by_index[name][mask_g].mean())
        group_rows.append(row)
    group_df = pd.DataFrame(group_rows)

    s1_scene_meta, s1_group_df = summarize_nearest_s1_for_scene(
        scene_date=scene_date,
        semantic_domain=semantic_domain,
        group_raster=group_raster,
        group_lut_records=group_lut_records,
        group_profile=group_profile,
        out_scene_dir=out_scene_dir,
    )

    group_df.to_csv(out_scene_dir / "group_scene_summary.csv", index=False)

    lookup_df = pd.DataFrame(lookup_logs)
    if not lookup_df.empty:
        enriched = []
        for rec in lookup_logs:
            row = env_lookup.get((str(rec["group_code"]), str(rec["index"]), str(rec["used_bin"])))
            if row is None:
                row = env[(env["group_code"] == rec["group_code"]) & (env["index"] == rec["index"]) & (env["doy_bin_label"] == rec["used_bin"])].iloc[0]
            enriched.append({
                **rec,
                "env_q_low": row[ENVELOPE_LOW_COL],
                "env_q_high": row[ENVELOPE_HIGH_COL],
                "operational_width": _row_value(row, "operational_width", row[ENVELOPE_HIGH_COL] - row[ENVELOPE_LOW_COL]),
                "n_dates": _row_value(row, "n_dates"),
                "n_unique_dates": _row_value(row, "n_unique_dates", _row_value(row, "n_dates")),
                "n_scene_records": _row_value(row, "n_scene_records"),
                "support_pixels_total": _row_value(row, "support_pixels_total"),
                "envelope_confidence": confidence_from_row(row),
                "envelope_confidence_code": confidence_code_from_row(row),
                "low_support_flag": _as_bool(_row_value(row, "low_support_flag", False)),
                "low_temporal_support_flag": _as_bool(_row_value(row, "low_temporal_support_flag", False)),
                "support_pixels_total_low_flag": _as_bool(_row_value(row, "support_pixels_total_low_flag", False)),
                "confidence_reason": _row_value(row, "confidence_reason", ""),
            })
        lookup_df = pd.DataFrame(enriched)
        lookup_df.to_csv(out_scene_dir / "group_lookup_used.csv", index=False)

    n_domain = int(semantic_domain.sum())
    scene_summary = {
        "scene": scene,
        "scene_key": scene_key,
        "date": scene_date.date().isoformat(),
        "doy": scene_doy,
        "doy_bin_label": bin_label,
        "n_grouped_valid_px": n_domain,
        "keep_px": int(keep.sum()),
        "drop_px": int(drop.sum()),
        "keep_pct": float(100.0 * keep.sum() / n_domain) if n_domain else np.nan,
        "drop_pct": float(100.0 * drop.sum() / n_domain) if n_domain else np.nan,
        "n_group_ids_used": int(group_df["group_id"].nunique()) if not group_df.empty else 0,
        "n_fallback_lookups": int(lookup_df["fallback_used"].sum()) if not lookup_df.empty else 0,
        "n_total_lookups": int(len(lookup_df)),
        "scl_available": bool(scene_row.get("scl_available", False)),
        "scl_used": bool(scene_row.get("scl_used", False)),
        "processed_from_phase3_cache": True,
        "cache_clear_mask_path": str(scene_row["clear_mask_path"]),
        "cache_index_stack_path": str(scene_row["index_stack_path"]),
        **s1_scene_meta,
        "write_anomaly_score": WRITE_ANOMALY_SCORE,
        "write_envelope_confidence_mask": WRITE_ENVELOPE_CONFIDENCE_MASK,
        "n_high_confidence_lookups": int((lookup_df["envelope_confidence"] == "high").sum()) if not lookup_df.empty and "envelope_confidence" in lookup_df.columns else 0,
        "n_medium_confidence_lookups": int((lookup_df["envelope_confidence"] == "medium").sum()) if not lookup_df.empty and "envelope_confidence" in lookup_df.columns else 0,
        "n_low_confidence_lookups": int((lookup_df["envelope_confidence"] == "low").sum()) if not lookup_df.empty and "envelope_confidence" in lookup_df.columns else 0,
        "n_missing_or_unknown_confidence_lookups": int(lookup_df["envelope_confidence"].isin(["missing", "unknown"]).sum()) if not lookup_df.empty and "envelope_confidence" in lookup_df.columns else 0,
        "n_groups_low_core_confidence": int((group_df["core_envelope_confidence"] == "low").sum()) if not group_df.empty and "core_envelope_confidence" in group_df.columns else 0,
        "mean_anomaly_score": float(np.nanmean(anomaly_score[semantic_domain])) if anomaly_score is not None and n_domain else np.nan,
        "core_indices": ",".join(CORE_INDICES),
        "keep_votes_required": KEEP_VOTES_REQUIRED,
    }
    return scene_summary, group_df, lookup_df


# =============================================================================
# Main
# =============================================================================


def main() -> None:
    t0 = time.time()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    require_cache_file(CACHE_ROOT / "preprocessing_manifest.json")
    manifest = read_json(CACHE_ROOT / "preprocessing_manifest.json")

    inv_all = load_scene_inventory_with_recommendations()
    target_inv, eligibility_df = filter_inventory_by_recommendation(inv_all)
    target_inv, eligibility_df = deduplicate_inventory_by_date(target_inv, eligibility_df)
    eligibility_df.to_csv(OUTPUT_DIR / "scene_eligibility_filter.csv", index=False)
    if target_inv.empty:
        raise RuntimeError(
            f"Scene filter policy {ENVELOPE_RUN!r} excluded all target scenes. "
            f"See {OUTPUT_DIR / 'scene_eligibility_filter.csv'}"
        )

    env = load_envelopes()
    env_lookup = build_envelope_lookup(env)
    group_raster, group_profile = read_int_raster(require_cache_file(CACHE_ROOT / "all_fmu_group_id.tif"))
    group_lut = pd.read_csv(require_cache_file(CACHE_ROOT / "group_lut_all_fmu.csv"))

    log(f"Selected envelope run: {ENVELOPE_RUN}")
    log(f"Phase 3 cache root: {CACHE_ROOT}")
    log(f"Cache scene count: {len(inv_all)}")
    log(f"Target scenes after filter/date deduplication: {len(target_inv)}")

    scene_rows = []
    group_rows_all = []
    lookup_rows_all = []
    for i, (_, row) in enumerate(target_inv.sort_values(["date", "scene"]).iterrows(), start=1):
        log(f"Processing cached scene [{i}/{len(target_inv)}] {row['scene']} ...")
        scene_summary, group_df, lookup_df = process_cached_scene(row, env, env_lookup, group_raster, group_profile, group_lut)
        scene_rows.append(scene_summary)
        if not group_df.empty:
            group_rows_all.append(group_df)
        if not lookup_df.empty:
            tmp = lookup_df.copy()
            tmp.insert(0, "scene", row["scene"])
            lookup_rows_all.append(tmp)

    pd.DataFrame(scene_rows).sort_values(["date", "scene"]).to_csv(OUTPUT_DIR / "scene_summary.csv", index=False)
    if group_rows_all:
        pd.concat(group_rows_all, ignore_index=True).to_csv(OUTPUT_DIR / "group_scene_summary_all.csv", index=False)
    if lookup_rows_all:
        pd.concat(lookup_rows_all, ignore_index=True).to_csv(OUTPUT_DIR / "lookup_trace_all.csv", index=False)

    readme = OUTPUT_DIR / "README.txt"
    readme.write_text(
        "Algorithm #2 Phase 5 semantic keep/drop masking using optical envelopes plus optional Sentinel-1 descriptor summaries.\n\n"
        f"Phase 3 cache root: {CACHE_ROOT}\n"
        f"Cache zip count: {manifest.get('zip_count')}\n"
        f"Envelope source: {ENVELOPE_SOURCE.name}\n"
        f"Target scene count before scene filter: {len(inv_all)}\n"
        f"Target scene count after scene filter/date deduplication: {len(target_inv)}\n"
        f"Scene filter policy: {ENVELOPE_RUN}; allowed recommendations: {';'.join(sorted(allowed_recommendations_for_envelope_run(ENVELOPE_RUN)))}\n"
        f"Deduplicate scenes by acquisition date: {DEDUPLICATE_TARGET_SCENES_BY_DATE}\n"
        "Input rasters were read from Phase 3 cache, not directly from Sentinel-2 ZIP scenes.\n"
        f"Sentinel-1 descriptor summaries enabled: {ENABLE_S1_DESCRIPTOR_SUMMARIES}\n"
        f"Sentinel-1 cache root: {S1_CACHE_ROOT}\n"
        f"Sentinel-1 maximum date offset: {S1_MAX_ABS_DATE_OFFSET_DAYS} days\n"
        f"Core indices: {', '.join(CORE_INDICES)}\n"
        f"Optional indices: {', '.join(OPTIONAL_INDICES) if OPTIONAL_INDICES else 'None'}\n"
        f"Keep rule: keep if at least {KEEP_VOTES_REQUIRED} of {len(CORE_INDICES)} core indices fall inside the healthy envelope\n"
        f"Envelope columns used: {ENVELOPE_LOW_COL}, {ENVELOPE_HIGH_COL}\n"
        f"Write anomaly-score raster: {WRITE_ANOMALY_SCORE}; nodata = {ANOMALY_SCORE_NODATA}\n"
        f"Write envelope-confidence mask: {WRITE_ENVELOPE_CONFIDENCE_MASK}; values = {ENVELOPE_CONFIDENCE_VALUES}\n"
        "Phase 4 confidence/anomaly outputs are diagnostic and do not change the default keep/drop rule.\n"
        f"DOY bin width: {DOY_BIN_WIDTH}\n"
        f"Fallback: {'nearest DOY bin' if USE_NEAREST_BIN_FALLBACK else 'none'}\n"
        "Valid domain: cached clear pixels inside grouped FMU polygons with finite core indices.\n",
        encoding="utf-8",
    )
    log(f"Done in {time.time() - t0:.1f}s. Outputs in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
