"""
Algorithm #1 Phase 5. Empirical optical envelopes plus optional Sentinel-1 descriptor envelopes.

This version consumes the Phase 3 preprocessing cache generated by:
    preprocess_sdv_sentinel2_shared_cache_phase3.py

It no longer reopens Sentinel-2 ZIP scenes or recomputes SCL masks / spectral indices.
Instead it reads:
- scene_inventory.csv
- scene_blacklist_recommendation.csv
- stable_support_group_id.tif
- group_lut_stable_support.csv
- clear_masks/*.tif
- index_stacks/*.tif

The final optical outputs remain compatible with Algorithm #2, including the ZIP bundle:
    sdv_si_empirical_envelopes_per_compositional_group_blacklist_and_caution.zip
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List
import shutil
import time
import warnings

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sdv_shared import (
    S1_DESCRIPTOR_BANDS,
    doy_bin_center,
    doy_bin_label,
    load_s1_inventory,
    read_json,
    read_uint8_mask,
    read_uint8_raster,
    read_int_raster,
    read_float32_stack,
    same_grid,
    zip_output_directory,
)

# =============================================================================
# HARD-CODED CONFIG
# =============================================================================

CACHE_ROOT = Path("D:/Forest_Disturbance/outputs/sdv_phase3_preprocessing_cache")
S1_CACHE_ROOT = Path("D:/Forest_Disturbance/outputs/sdv_phase5_sentinel1_descriptor_cache")

GROUP_WORKBOOK = Path("D:/Forest_Disturbance/tables/sdv_compos_groups_loss_causes_reference.xlsx")
GROUP_SHEET = "LOSS_CAUSES"
GROUP_CODE_FIELD = "COMPOZ_TYPE_CODE"
GROUP_LABEL_FIELD = "COMPOZ_TYPE_LABEL"
EXCLUDE_GROUP_CODES = {"NO_DATA"}

DOY_BIN_WIDTH = 30
ENV_Q_LOW = 0.10
ENV_Q_HIGH = 0.90

# Phase 4 envelope-confidence diagnostics. These annotations do not change the
# empirical envelope values; they make low-support seasonal bins explicit.
ENVELOPE_CONFIDENCE_HIGH_MIN_UNIQUE_DATES = 5
ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES = 3
MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE = 1000
WRITE_ENVELOPE_QUALITY_TABLES = True

USE_INDICES = ["NDVI", "NDMI", "NBR", "NDRE"]
INDEX_STACK_BANDS = ["NDVI", "NDMI", "NBR", "NDRE", "NDSI"]

# Phase 5 Sentinel-1 descriptor envelopes. These are written separately from
# the optical doy_bin_envelopes.csv so Algorithm #2 remains backward compatible.
INCLUDE_S1_DESCRIPTOR_ENVELOPES = True
# Use "auto" to summarize only Sentinel-1 descriptors that are actually
# present in the Phase 5 v3 S1 cache. This avoids all-nodata VV rows when
# the EO Browser ZIPs contain VH only.
S1_DESCRIPTOR_BANDS_FOR_ENVELOPES = "auto"
S1_DESCRIPTOR_EXCLUDE_FROM_ENVELOPES = {"S1_VALID"}
S1_MIN_PIXELS_PER_GROUP_DATE = 50

# Scene-quality controls. Options: "none", "blacklist", "blacklist_and_caution".
SCENE_FILTER_MODE = "blacklist_and_caution"
MIN_PIXELS_PER_GROUP_DATE = 50
WRITE_INTERMEDIATE = True
VERBOSE = True

OUTPUT_DIR = Path("D:/Forest_Disturbance/outputs/sdv_si_empirical_envelopes_per_compositional_group_blacklist_and_caution")
PLOTS_DIRNAME = "plots"
WRITE_OUTPUT_ZIP = True
OUTPUT_ZIP = OUTPUT_DIR.with_suffix(".zip")

# Plot generation. These options restore the plotting controls from the original
# Algorithm #1 while keeping the Phase 3 cache-based processing path.
MAKE_PLOTS = True
MIN_DATES_PER_BIN_FOR_PLOT = 1
CLEAR_PLOTS_DIR_BEFORE_WRITE = True

# Which date-level records are displayed as points:
# - "unique_date": uses duplicate-date-collapsed rows, matching the envelope aggregation.
# - "scene_records": uses every retained scene record, useful for seeing duplicate scenes.
PLOT_DATE_SOURCE = "unique_date"

# Date-level point styling.
SHOW_DATE_MEDIAN_POINTS = True
COLOR_POINTS_BY_YEAR = True
CONNECT_POINTS_WITHIN_YEAR = False
YEAR_COLORMAP = "tab20"
SCATTER_SIZE = 24
SCATTER_ALPHA = 0.85
YEAR_LINEWIDTH = 0.9

# Envelope / curve display switches.
SHOW_ENVELOPE_BAND = True              # env_q_low .. env_q_high from date medians
SHOW_ENVELOPE_MEDIAN = True            # env_q_med
SHOW_CURVE_MIN_MAX = True              # curve_min .. curve_max, i.e. min/max of date medians
SHOW_OPERATIONAL_Q10_Q90 = False       # median_of_date_q10 / median_of_date_q90, used by Algorithm #2
SHOW_PIXEL_MIN_MAX_RANGE = False       # min_of_date_min / max_of_date_max, can be noisy
SHOW_LOW_CONFIDENCE_BIN_MARKERS = True # vertical markers for low-confidence DOY-bin envelopes

# Optional date-level vertical ranges around each point.
SHOW_DATE_Q10_Q90_RANGES = False       # date_q10 .. date_q90 for each date/group/index
SHOW_DATE_MIN_MAX_RANGES = False       # date_min .. date_max for each date/group/index; often visually noisy
DATE_RANGE_LINEWIDTH = 0.7
DATE_RANGE_ALPHA = 0.30

# Figure output.
PLOT_FIGSIZE = (8.6, 4.9)
PLOT_DPI = 180
PLOT_GRID_ALPHA = 0.25
PLOT_LEGEND = True

# =============================================================================
# Helpers
# =============================================================================


def log(msg: str) -> None:
    if VERBOSE:
        print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def require_cache_file(path: Path) -> Path:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Required Phase 3 cache file is missing: {path}\n"
            "Run preprocess_sdv_sentinel2_shared_cache_phase3.py before Algorithm #1 Phase 4."
        )
    return path


def copy_cache_file(name: str, output_name: str | None = None) -> None:
    src = CACHE_ROOT / name
    if src.exists():
        dst = OUTPUT_DIR / (output_name or name)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def allowed_scene_recommendations(mode: str) -> set[str]:
    mode = mode.lower().strip()
    if mode == "none":
        return {"keep", "caution", "blacklist"}
    if mode == "blacklist":
        return {"keep", "caution"}
    if mode == "blacklist_and_caution":
        return {"keep"}
    raise ValueError(f"Unsupported SCENE_FILTER_MODE: {mode!r}")


def _norm_codes(values) -> List[str]:
    out = []
    for value in values:
        if pd.isna(value):
            continue
        s = str(value).strip()
        if s and s.lower() != "nan":
            out.append(s)
    return sorted(set(out))


def emit_group_code_checks_cache(stable_lut: pd.DataFrame, env_df: pd.DataFrame) -> None:
    """Write group-code consistency diagnostics using cache group LUTs."""
    try:
        xls = pd.ExcelFile(GROUP_WORKBOOK)
        sheet = GROUP_SHEET if GROUP_SHEET in xls.sheet_names else xls.sheet_names[0]
        workbook_attrs = pd.read_excel(GROUP_WORKBOOK, sheet_name=sheet)
        workbook_raw_codes = _norm_codes(workbook_attrs.get(GROUP_CODE_FIELD, pd.Series(dtype=object)))
    except Exception as exc:
        warnings.warn(f"Could not load workbook group-code diagnostics: {exc}")
        workbook_raw_codes = []

    workbook_non_excluded_codes = [c for c in workbook_raw_codes if c not in EXCLUDE_GROUP_CODES]
    support_group_codes = _norm_codes(stable_lut.get("group_code", pd.Series(dtype=object)))
    raster_group_codes = support_group_codes
    envelope_group_codes = _norm_codes(env_df.get("group_code", pd.Series(dtype=object)))

    workbook_not_used_after_filters = [c for c in workbook_non_excluded_codes if c not in support_group_codes]
    missing_in_envelopes = [c for c in support_group_codes if c not in envelope_group_codes]
    extra_in_envelopes = [c for c in envelope_group_codes if c not in support_group_codes]

    log(f"Workbook group codes (raw): {workbook_raw_codes}")
    log(f"Workbook group codes (non-excluded): {workbook_non_excluded_codes}")
    log(f"Support group codes after stable/exclusion filters: {support_group_codes}")
    log(f"Rasterized group codes: {raster_group_codes}")
    log(f"Generated envelope group codes: {envelope_group_codes}")

    if workbook_not_used_after_filters:
        log("Info: workbook codes not used after stable/exclusion filters: " + ", ".join(workbook_not_used_after_filters))

    report_rows = []
    all_codes = sorted(set(workbook_raw_codes) | set(workbook_non_excluded_codes) | set(support_group_codes) | set(envelope_group_codes))
    for code in all_codes:
        report_rows.append({
            "group_code": code,
            "in_workbook_raw": code in workbook_raw_codes,
            "in_workbook_non_excluded": code in workbook_non_excluded_codes,
            "in_support_after_filters": code in support_group_codes,
            "in_raster_group_table": code in raster_group_codes,
            "in_generated_envelopes": code in envelope_group_codes,
        })
    pd.DataFrame(report_rows).to_csv(OUTPUT_DIR / "group_code_check_report.csv", index=False)

    summary_lines = [
        f"Workbook group codes (raw): {', '.join(workbook_raw_codes) if workbook_raw_codes else '(none)'}",
        f"Workbook group codes (non-excluded): {', '.join(workbook_non_excluded_codes) if workbook_non_excluded_codes else '(none)'}",
        f"Support group codes after stable/exclusion filters: {', '.join(support_group_codes) if support_group_codes else '(none)'}",
        f"Rasterized group codes: {', '.join(raster_group_codes) if raster_group_codes else '(none)'}",
        f"Generated envelope group codes: {', '.join(envelope_group_codes) if envelope_group_codes else '(none)'}",
    ]
    if missing_in_envelopes:
        msg = "WARNING: support group codes missing from generated envelopes: " + ", ".join(missing_in_envelopes)
        warnings.warn(msg)
        log(msg)
        summary_lines.append(msg)
    else:
        ok_msg = "Support group codes and generated envelope group codes match."
        log(ok_msg)
        summary_lines.append(ok_msg)
    if extra_in_envelopes:
        msg = "WARNING: envelope group codes not present in support groups: " + ", ".join(extra_in_envelopes)
        warnings.warn(msg)
        log(msg)
        summary_lines.append(msg)
    (OUTPUT_DIR / "group_code_check_summary.txt").write_text("\n".join(summary_lines), encoding="utf-8")


def collapse_duplicate_date_rows(date_df: pd.DataFrame) -> pd.DataFrame:
    group_cols = [
        "date", "year", "month", "day", "doy", "doy_bin_label", "doy_bin_center",
        "group_id", "group_code", "group_label", "index",
    ]
    agg = {
        "zip_file": lambda x: ";".join(sorted(set(map(str, x)))),
        "n_valid_pixels": "sum",
        "date_min": "min",
        "date_q10": "median",
        "date_median": "median",
        "date_q90": "median",
        "date_max": "max",
        "date_mean": "mean",
    }
    out = date_df.groupby(group_cols, dropna=False, as_index=False).agg(agg)
    counts = date_df.groupby(group_cols, dropna=False)["zip_file"].count().reset_index(name="n_scene_records")
    out = out.merge(counts, on=group_cols, how="left")
    ordered = [
        "zip_file", "n_scene_records", "date", "year", "month", "day", "doy",
        "doy_bin_label", "doy_bin_center", "group_id", "group_code", "group_label",
        "index", "n_valid_pixels", "date_min", "date_q10", "date_median",
        "date_q90", "date_max", "date_mean",
    ]
    return out[ordered].sort_values(["group_code", "index", "date"]).reset_index(drop=True)


def envelope_confidence_code(n_unique_dates: int, support_pixels_total: int) -> int:
    """Return 3=high, 2=medium, 1=low, 0=missing envelope support."""
    try:
        n_unique_dates = int(n_unique_dates)
    except Exception:
        n_unique_dates = 0
    try:
        support_pixels_total = int(support_pixels_total)
    except Exception:
        support_pixels_total = 0

    if n_unique_dates <= 0 or support_pixels_total <= 0:
        return 0
    if n_unique_dates >= ENVELOPE_CONFIDENCE_HIGH_MIN_UNIQUE_DATES:
        return 3
    if (
        n_unique_dates >= ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES
        and support_pixels_total >= MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE
    ):
        return 2
    return 1


def envelope_confidence_label(code: int) -> str:
    """Return a text label for the envelope-confidence code."""
    return {3: "high", 2: "medium", 1: "low", 0: "missing"}.get(int(code), "unknown")


def write_envelope_quality_tables(env_df: pd.DataFrame) -> None:
    """Write Phase 4 support/confidence diagnostics for envelope rows."""
    if not WRITE_ENVELOPE_QUALITY_TABLES or env_df.empty:
        return

    quality_cols = [
        "group_code", "group_label", "index", "doy_bin_label", "doy_bin_center",
        "n_unique_dates", "n_scene_records", "support_pixels_total",
        "support_pixels_per_date_min", "support_pixels_per_date_mean",
        "env_q_width", "operational_width",
        "envelope_confidence", "envelope_confidence_code",
        "low_support_flag", "low_temporal_support_flag", "support_pixels_total_low_flag",
    ]
    cols = [c for c in quality_cols if c in env_df.columns]
    env_df[cols].to_csv(OUTPUT_DIR / "doy_bin_envelope_quality.csv", index=False)

    summary = (
        env_df.groupby(["envelope_confidence", "envelope_confidence_code"], dropna=False)
        .size()
        .reset_index(name="n_envelope_rows")
        .sort_values(["envelope_confidence_code", "envelope_confidence"], ascending=[False, True])
    )
    summary.to_csv(OUTPUT_DIR / "doy_bin_envelope_quality_summary.csv", index=False)

    by_doy = (
        env_df.groupby(["doy_bin_label", "envelope_confidence"], dropna=False)
        .size()
        .reset_index(name="n_envelope_rows")
        .sort_values(["doy_bin_label", "envelope_confidence"])
    )
    by_doy.to_csv(OUTPUT_DIR / "doy_bin_envelope_quality_by_doy_bin.csv", index=False)

    by_group_index = (
        env_df.groupby(["group_code", "index"], dropna=False)
        .agg(
            n_envelope_rows=("envelope_confidence_code", "size"),
            min_confidence_code=("envelope_confidence_code", "min"),
            low_confidence_rows=("low_support_flag", "sum"),
            min_unique_dates=("n_unique_dates", "min"),
            median_unique_dates=("n_unique_dates", "median"),
            max_unique_dates=("n_unique_dates", "max"),
        )
        .reset_index()
        .sort_values(["group_code", "index"])
    )
    by_group_index.to_csv(OUTPUT_DIR / "doy_bin_envelope_quality_by_group_index.csv", index=False)


def _plot_options_dict() -> dict:
    """Return plot configuration for reproducibility."""
    return {
        "MAKE_PLOTS": MAKE_PLOTS,
        "MIN_DATES_PER_BIN_FOR_PLOT": MIN_DATES_PER_BIN_FOR_PLOT,
        "CLEAR_PLOTS_DIR_BEFORE_WRITE": CLEAR_PLOTS_DIR_BEFORE_WRITE,
        "PLOT_DATE_SOURCE": PLOT_DATE_SOURCE,
        "SHOW_DATE_MEDIAN_POINTS": SHOW_DATE_MEDIAN_POINTS,
        "COLOR_POINTS_BY_YEAR": COLOR_POINTS_BY_YEAR,
        "CONNECT_POINTS_WITHIN_YEAR": CONNECT_POINTS_WITHIN_YEAR,
        "YEAR_COLORMAP": YEAR_COLORMAP,
        "SCATTER_SIZE": SCATTER_SIZE,
        "SCATTER_ALPHA": SCATTER_ALPHA,
        "YEAR_LINEWIDTH": YEAR_LINEWIDTH,
        "SHOW_ENVELOPE_BAND": SHOW_ENVELOPE_BAND,
        "SHOW_ENVELOPE_MEDIAN": SHOW_ENVELOPE_MEDIAN,
        "SHOW_CURVE_MIN_MAX": SHOW_CURVE_MIN_MAX,
        "SHOW_OPERATIONAL_Q10_Q90": SHOW_OPERATIONAL_Q10_Q90,
        "SHOW_PIXEL_MIN_MAX_RANGE": SHOW_PIXEL_MIN_MAX_RANGE,
        "SHOW_LOW_CONFIDENCE_BIN_MARKERS": SHOW_LOW_CONFIDENCE_BIN_MARKERS,
        "ENVELOPE_CONFIDENCE_HIGH_MIN_UNIQUE_DATES": ENVELOPE_CONFIDENCE_HIGH_MIN_UNIQUE_DATES,
        "ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES": ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES,
        "MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE": MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE,
        "SHOW_DATE_Q10_Q90_RANGES": SHOW_DATE_Q10_Q90_RANGES,
        "SHOW_DATE_MIN_MAX_RANGES": SHOW_DATE_MIN_MAX_RANGES,
        "DATE_RANGE_LINEWIDTH": DATE_RANGE_LINEWIDTH,
        "DATE_RANGE_ALPHA": DATE_RANGE_ALPHA,
        "PLOT_FIGSIZE": str(PLOT_FIGSIZE),
        "PLOT_DPI": PLOT_DPI,
        "PLOT_GRID_ALPHA": PLOT_GRID_ALPHA,
        "PLOT_LEGEND": PLOT_LEGEND,
    }


def _prepare_plots_dir() -> Path:
    plots_dir = OUTPUT_DIR / PLOTS_DIRNAME
    plots_dir.mkdir(parents=True, exist_ok=True)
    if CLEAR_PLOTS_DIR_BEFORE_WRITE:
        for png in plots_dir.glob("*.png"):
            png.unlink()
    pd.DataFrame([_plot_options_dict()]).to_csv(OUTPUT_DIR / "plot_options_used.csv", index=False)
    return plots_dir


def _scatter_or_range_by_year(ax, pts: pd.DataFrame) -> None:
    """Plot date-level points, optionally colored and connected by year."""
    if pts.empty or not SHOW_DATE_MEDIAN_POINTS:
        return

    pts = pts.copy()
    pts["date"] = pd.to_datetime(pts["date"], errors="coerce")
    pts = pts[pts["date"].notna()].copy()
    if pts.empty:
        return
    pts["year"] = pts["date"].dt.year.astype(int)

    def _draw_ranges(data: pd.DataFrame, color=None) -> None:
        x = data["doy"].to_numpy(dtype=float)
        if SHOW_DATE_MIN_MAX_RANGES and {"date_min", "date_max"}.issubset(data.columns):
            ax.vlines(
                x,
                data["date_min"].to_numpy(dtype=float),
                data["date_max"].to_numpy(dtype=float),
                colors=color,
                linewidth=DATE_RANGE_LINEWIDTH,
                alpha=DATE_RANGE_ALPHA,
                label="_nolegend_",
            )
        if SHOW_DATE_Q10_Q90_RANGES and {"date_q10", "date_q90"}.issubset(data.columns):
            ax.vlines(
                x,
                data["date_q10"].to_numpy(dtype=float),
                data["date_q90"].to_numpy(dtype=float),
                colors=color,
                linewidth=max(DATE_RANGE_LINEWIDTH, 1.0),
                alpha=min(DATE_RANGE_ALPHA + 0.15, 1.0),
                label="_nolegend_",
            )

    if COLOR_POINTS_BY_YEAR:
        years = sorted(pts["year"].dropna().unique().tolist())
        cmap = plt.get_cmap(YEAR_COLORMAP, max(len(years), 1))
        year_to_color = {yr: cmap(i) for i, yr in enumerate(years)}

        for yr in years:
            ysub = pts[pts["year"] == yr].sort_values("doy")
            color = year_to_color[yr]
            _draw_ranges(ysub, color=color)
            ax.scatter(
                ysub["doy"],
                ysub["date_median"],
                s=SCATTER_SIZE,
                alpha=SCATTER_ALPHA,
                color=color,
                label=f"{yr} date medians",
            )
            if CONNECT_POINTS_WITHIN_YEAR and len(ysub) >= 2:
                ax.plot(
                    ysub["doy"],
                    ysub["date_median"],
                    linestyle=":",
                    linewidth=YEAR_LINEWIDTH,
                    alpha=min(SCATTER_ALPHA + 0.05, 1.0),
                    color=color,
                    label="_nolegend_",
                )
    else:
        pts = pts.sort_values("doy")
        _draw_ranges(pts, color=None)
        ax.scatter(
            pts["doy"],
            pts["date_median"],
            s=SCATTER_SIZE,
            alpha=SCATTER_ALPHA,
            label="Date medians",
        )


def write_optional_plots(env_df: pd.DataFrame, date_df_for_plot: pd.DataFrame) -> None:
    """Write envelope plots with the original selectable display capabilities restored.

    Each plot is generated for one analytical group and one spectral index.
    The display can include the envelope band, envelope median, min/max date-median
    curves, operational q10/q90 bounds, pixel min/max bounds, date-level points
    colored by year, and optional within-year connections.
    """
    if not MAKE_PLOTS:
        log("Finished envelope aggregation; skipping plot generation (MAKE_PLOTS=False)")
        pd.DataFrame([_plot_options_dict()]).to_csv(OUTPUT_DIR / "plot_options_used.csv", index=False)
        return

    log("Finished envelope aggregation; starting plots")
    plots_dir = _prepare_plots_dir()
    n_plots = 0

    for (group_code, group_label, index_name), sub in env_df.groupby(["group_code", "group_label", "index"], dropna=False):
        sub = sub.sort_values("doy_bin_center")
        if len(sub) < MIN_DATES_PER_BIN_FOR_PLOT:
            continue

        x = sub["doy_bin_center"].to_numpy(dtype=float)
        fig, ax = plt.subplots(figsize=PLOT_FIGSIZE)

        if SHOW_LOW_CONFIDENCE_BIN_MARKERS and "envelope_confidence" in sub.columns:
            low_conf = sub[sub["envelope_confidence"].astype(str).str.lower().isin(["low", "missing"])]
            first_marker = True
            for xc in low_conf["doy_bin_center"].to_numpy(dtype=float):
                ax.axvline(
                    xc,
                    linestyle=":",
                    linewidth=0.8,
                    alpha=0.20,
                    label="Low-confidence DOY bin" if first_marker else "_nolegend_",
                )
                first_marker = False

        if SHOW_ENVELOPE_BAND:
            env_low = sub["env_q_low"].to_numpy(dtype=float)
            env_high = sub["env_q_high"].to_numpy(dtype=float)
            ax.fill_between(
                x,
                env_low,
                env_high,
                alpha=0.20,
                label=f"Envelope q{int(ENV_Q_LOW * 100)}–q{int(ENV_Q_HIGH * 100)}",
            )

        if SHOW_ENVELOPE_MEDIAN:
            ax.plot(
                x,
                sub["env_q_med"].to_numpy(dtype=float),
                linewidth=2.0,
                label="Envelope median (q50)",
            )

        if SHOW_CURVE_MIN_MAX and {"curve_min", "curve_max"}.issubset(sub.columns):
            ax.plot(
                x,
                sub["curve_min"].to_numpy(dtype=float),
                linestyle="--",
                linewidth=1.3,
                label="Min of date medians",
            )
            ax.plot(
                x,
                sub["curve_max"].to_numpy(dtype=float),
                linestyle="--",
                linewidth=1.3,
                label="Max of date medians",
            )

        if SHOW_OPERATIONAL_Q10_Q90 and {"median_of_date_q10", "median_of_date_q90"}.issubset(sub.columns):
            ax.plot(
                x,
                sub["median_of_date_q10"].to_numpy(dtype=float),
                linestyle="-.",
                linewidth=1.1,
                label="Median of date q10",
            )
            ax.plot(
                x,
                sub["median_of_date_q90"].to_numpy(dtype=float),
                linestyle="-.",
                linewidth=1.1,
                label="Median of date q90",
            )

        if SHOW_PIXEL_MIN_MAX_RANGE and {"min_of_date_min", "max_of_date_max"}.issubset(sub.columns):
            ax.plot(
                x,
                sub["min_of_date_min"].to_numpy(dtype=float),
                linestyle=":",
                linewidth=1.0,
                alpha=0.75,
                label="Min of date minima",
            )
            ax.plot(
                x,
                sub["max_of_date_max"].to_numpy(dtype=float),
                linestyle=":",
                linewidth=1.0,
                alpha=0.75,
                label="Max of date maxima",
            )

        pts = date_df_for_plot[
            (date_df_for_plot["group_code"] == group_code)
            & (date_df_for_plot["index"] == index_name)
        ].copy()
        _scatter_or_range_by_year(ax, pts)

        ax.set_xlim(1, 365)
        ax.set_xticks([1, 60, 120, 180, 240, 300, 365])
        ax.set_xlabel("DOY")
        ax.set_ylabel(str(index_name))
        ax.set_title(f"{group_code} — {index_name}")
        ax.grid(True, alpha=PLOT_GRID_ALPHA)
        if PLOT_LEGEND:
            ax.legend(loc="best", fontsize=8)
        fig.tight_layout()
        safe_name = f"{group_code}_{index_name}_envelope.png".replace("/", "_")
        fig.savefig(plots_dir / safe_name, dpi=PLOT_DPI, bbox_inches="tight")
        plt.close(fig)
        n_plots += 1

    log(f"Finished plot generation: {n_plots} PNG files in {plots_dir}")



def resolve_s1_descriptors_for_envelopes(s1_inventory: pd.DataFrame) -> List[str]:
    """Resolve Sentinel-1 descriptors to summarize.

    In Phase 5 v3 the S1 cache records descriptor_bands_available per scene.
    With S1_DESCRIPTOR_BANDS_FOR_ENVELOPES = "auto", only descriptors with
    actual finite data are used. Binary validity and unavailable VV descriptors
    are excluded.
    """
    cfg = S1_DESCRIPTOR_BANDS_FOR_ENVELOPES
    if isinstance(cfg, str) and cfg.lower().strip() == "auto":
        found = []
        if "descriptor_bands_available" in s1_inventory.columns:
            for txt in s1_inventory["descriptor_bands_available"].fillna("").astype(str):
                for name in [x.strip() for x in txt.split(",") if x.strip()]:
                    if name not in found and name not in S1_DESCRIPTOR_EXCLUDE_FROM_ENVELOPES:
                        found.append(name)
        if not found:
            # Backward compatible fallback for older S1 caches.
            found = [
                name for name in S1_DESCRIPTOR_BANDS
                if name not in S1_DESCRIPTOR_EXCLUDE_FROM_ENVELOPES
            ]
        return found
    return [str(x) for x in cfg if str(x) not in S1_DESCRIPTOR_EXCLUDE_FROM_ENVELOPES]


def write_s1_descriptor_envelopes(stable_group_raster: np.ndarray, group_profile: dict, stable_lut: pd.DataFrame) -> pd.DataFrame:
    """Generate separate Sentinel-1 descriptor envelopes from the Phase 5 S1 cache.

    The output uses the same column logic as the optical envelope table, but is
    written to s1_doy_bin_envelopes.csv. The main optical doy_bin_envelopes.csv
    remains unchanged for Algorithm #2 compatibility.
    """
    if not INCLUDE_S1_DESCRIPTOR_ENVELOPES:
        return pd.DataFrame()
    if not S1_CACHE_ROOT.exists():
        log(f"Sentinel-1 cache not found; skipping S1 descriptor envelopes: {S1_CACHE_ROOT}")
        return pd.DataFrame()
    s1_inv = load_s1_inventory(S1_CACHE_ROOT)
    if s1_inv.empty:
        log("Sentinel-1 inventory is empty; skipping S1 descriptor envelopes")
        return pd.DataFrame()

    available = s1_inv[s1_inv.get("cache_status", "").astype(str).str.lower().isin(["created", "rebuilt", "existing"])] if "cache_status" in s1_inv.columns else s1_inv
    if available.empty:
        log("No valid Sentinel-1 cached scenes available; skipping S1 descriptor envelopes")
        return pd.DataFrame()

    s1_descriptors_for_envelopes = resolve_s1_descriptors_for_envelopes(available)
    log(f"Sentinel-1 descriptors selected for envelope summarization: {', '.join(s1_descriptors_for_envelopes) if s1_descriptors_for_envelopes else 'none'}")

    support_domain = stable_group_raster > 0
    group_records = stable_lut[["group_id", "group_code", "group_label"]].drop_duplicates().itertuples(index=False)
    group_records = list(group_records)
    s1_rows: List[dict] = []

    for i_scene, row in enumerate(available.sort_values(["date", "scene"]).itertuples(index=False), start=1):
        scene = str(getattr(row, "scene"))
        s1_date = pd.Timestamp(getattr(row, "date"))
        stack_path = Path(getattr(row, "s1_stack_path"))
        valid_path = Path(getattr(row, "s1_valid_mask_path"))
        if not stack_path.exists() or not valid_path.exists():
            continue
        try:
            try:
                stack, stack_profile = read_float32_stack(stack_path, expected_names=S1_DESCRIPTOR_BANDS)
            except Exception:
                stack, stack_profile = read_float32_stack(stack_path)
            valid_arr, valid_profile = read_uint8_raster(valid_path)
            if not same_grid(stack_profile, group_profile) or not same_grid(valid_profile, group_profile):
                raise RuntimeError(f"S1 stack grid does not match stable support group raster for {scene}")
            valid_mask = (valid_arr == 1) & support_domain
            for group_id, group_code, group_label in group_records:
                group_mask = valid_mask & (stable_group_raster == int(group_id))
                if int(group_mask.sum()) < S1_MIN_PIXELS_PER_GROUP_DATE:
                    continue
                for descriptor in s1_descriptors_for_envelopes:
                    arr = stack.get(descriptor)
                    if arr is None:
                        continue
                    vals = arr[group_mask]
                    vals = vals[np.isfinite(vals)]
                    if vals.size < S1_MIN_PIXELS_PER_GROUP_DATE:
                        continue
                    doy = int(s1_date.dayofyear)
                    s1_rows.append({
                        "sensor": "S1",
                        "zip_file": scene,
                        "date": s1_date.date().isoformat(),
                        "year": int(s1_date.year),
                        "month": int(s1_date.month),
                        "day": int(s1_date.day),
                        "doy": doy,
                        "doy_bin_label": doy_bin_label(doy, DOY_BIN_WIDTH),
                        "doy_bin_center": doy_bin_center(doy, DOY_BIN_WIDTH),
                        "group_id": int(group_id),
                        "group_code": group_code,
                        "group_label": group_label,
                        "index": descriptor,
                        "descriptor": descriptor,
                        "n_valid_pixels": int(vals.size),
                        "date_min": float(np.min(vals)),
                        "date_q10": float(np.quantile(vals, 0.10)),
                        "date_median": float(np.median(vals)),
                        "date_q90": float(np.quantile(vals, 0.90)),
                        "date_max": float(np.max(vals)),
                        "date_mean": float(np.mean(vals)),
                    })
        except Exception as exc:
            log(f"WARNING: could not summarize S1 descriptors for {scene}: {exc}")
            continue
        log(f"[S1 {i_scene}/{len(available)}] summarized {scene}; cumulative S1 rows = {len(s1_rows)}")

    if not s1_rows:
        log("No Sentinel-1 descriptor rows were generated")
        return pd.DataFrame()

    s1_date_df = pd.DataFrame(s1_rows).sort_values(["group_code", "index", "date", "zip_file"]).reset_index(drop=True)
    s1_date_df.to_csv(OUTPUT_DIR / "s1_date_group_descriptor_medians.csv", index=False)
    s1_unique_df = collapse_duplicate_date_rows(s1_date_df)
    s1_unique_df["sensor"] = "S1"
    s1_unique_df["descriptor"] = s1_unique_df["index"]
    s1_unique_df.to_csv(OUTPUT_DIR / "s1_date_group_descriptor_medians_by_unique_date.csv", index=False)

    env_rows = []
    group_cols = ["group_code", "group_label", "index", "doy_bin_label", "doy_bin_center"]
    for keys, sub in s1_unique_df.groupby(group_cols, dropna=False):
        group_code, group_label, descriptor, bin_label, bin_center = keys
        medians = sub["date_median"].to_numpy(dtype=float)
        q10s = sub["date_q10"].to_numpy(dtype=float)
        q90s = sub["date_q90"].to_numpy(dtype=float)
        mins = sub["date_min"].to_numpy(dtype=float)
        maxs = sub["date_max"].to_numpy(dtype=float)
        n_unique_dates = int(sub["date"].nunique())
        n_scene_records = int(sub.get("n_scene_records", pd.Series([1] * len(sub), index=sub.index)).sum())
        support_pixels_total = int(sub["n_valid_pixels"].sum())
        support_pixels_per_date_min = int(sub["n_valid_pixels"].min())
        support_pixels_per_date_mean = float(sub["n_valid_pixels"].mean())
        env_q_low = float(np.quantile(medians, ENV_Q_LOW))
        env_q_med = float(np.quantile(medians, 0.50))
        env_q_high = float(np.quantile(medians, ENV_Q_HIGH))
        median_of_date_q10 = float(np.median(q10s))
        median_of_date_q90 = float(np.median(q90s))
        confidence_code = envelope_confidence_code(n_unique_dates, support_pixels_total)
        env_rows.append({
            "sensor": "S1",
            "group_code": group_code,
            "group_label": group_label,
            "index": descriptor,
            "descriptor": descriptor,
            "doy_bin_label": bin_label,
            "doy_bin_center": int(bin_center),
            "n_dates": n_unique_dates,
            "n_unique_dates": n_unique_dates,
            "n_scene_records": n_scene_records,
            "support_pixels_total": support_pixels_total,
            "support_pixels_per_date_min": support_pixels_per_date_min,
            "support_pixels_per_date_mean": support_pixels_per_date_mean,
            "env_q_low": env_q_low,
            "env_q_med": env_q_med,
            "env_q_high": env_q_high,
            "env_q_width": float(env_q_high - env_q_low),
            "curve_min": float(np.min(medians)),
            "curve_med": float(np.median(medians)),
            "curve_max": float(np.max(medians)),
            "median_of_date_q10": median_of_date_q10,
            "median_of_date_q90": median_of_date_q90,
            "operational_width": float(median_of_date_q90 - median_of_date_q10),
            "min_of_date_min": float(np.min(mins)),
            "max_of_date_max": float(np.max(maxs)),
            "envelope_confidence": envelope_confidence_label(confidence_code),
            "envelope_confidence_code": confidence_code,
            "low_support_flag": bool(confidence_code < 2),
            "low_temporal_support_flag": bool(n_unique_dates < ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES),
            "support_pixels_total_low_flag": bool(support_pixels_total < MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE),
        })
    s1_env = pd.DataFrame(env_rows).sort_values(["group_code", "index", "doy_bin_center"]).reset_index(drop=True)
    s1_env.to_csv(OUTPUT_DIR / "s1_doy_bin_envelopes.csv", index=False)

    s1_quality = (
        s1_env.groupby(["envelope_confidence", "envelope_confidence_code"], dropna=False)
        .size().reset_index(name="n_s1_envelope_rows")
        .sort_values("envelope_confidence_code")
    )
    s1_quality.to_csv(OUTPUT_DIR / "s1_doy_bin_envelope_quality_summary.csv", index=False)
    coverage = (
        s1_unique_df.groupby(["group_code", "index"])
        .agg(n_dates=("date", "nunique"), n_scene_records=("n_scene_records", "sum"), min_doy=("doy", "min"), max_doy=("doy", "max"))
        .reset_index().sort_values(["group_code", "index"])
    )
    coverage.to_csv(OUTPUT_DIR / "s1_group_descriptor_date_coverage.csv", index=False)
    log(f"Wrote Sentinel-1 descriptor envelopes: {len(s1_env)} rows")
    return s1_env

# =============================================================================
# Main
# =============================================================================


def main() -> None:
    t0 = time.time()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    log("Starting empirical envelope extraction from Phase 3 cache")

    require_cache_file(CACHE_ROOT / "preprocessing_manifest.json")
    manifest = read_json(CACHE_ROOT / "preprocessing_manifest.json")
    inv = pd.read_csv(require_cache_file(CACHE_ROOT / "scene_inventory.csv"))
    rec = pd.read_csv(require_cache_file(CACHE_ROOT / "scene_blacklist_recommendation.csv"))
    stable_lut = pd.read_csv(require_cache_file(CACHE_ROOT / "group_lut_stable_support.csv"))
    group_raster, group_profile = read_int_raster(require_cache_file(CACHE_ROOT / "stable_support_group_id.tif"))
    support_domain = group_raster > 0

    # Copy cache diagnostics to the Algorithm #1 output folder.
    for filename in [
        "scene_inventory.csv",
        "scene_quality_summary.csv",
        "scene_blacklist_recommendation.csv",
        "stable_subparcels_used.geojson",
        "stable_support_by_group.csv",
        "preprocessing_manifest.json",
    ]:
        copy_cache_file(filename)

    if "recommendation" not in inv.columns:
        inv = inv.merge(rec[["scene", "recommendation", "recommendation_reason"]], on="scene", how="left")
    inv["recommendation"] = inv["recommendation"].astype(str).str.lower().str.strip()

    allowed = allowed_scene_recommendations(SCENE_FILTER_MODE)
    used = inv[inv["recommendation"].isin(allowed)].copy()
    if used.empty:
        raise RuntimeError(f"Scene filter mode {SCENE_FILTER_MODE!r} excluded all scenes.")
    log(f"Cache contains {len(inv)} scenes; {len(used)} scenes remain after mode {SCENE_FILTER_MODE!r}")

    date_rows: List[dict] = []
    intermediate_path = OUTPUT_DIR / "date_group_index_medians_intermediate.csv"
    if WRITE_INTERMEDIATE and intermediate_path.exists():
        intermediate_path.unlink()

    group_records = stable_lut[["group_id", "group_code", "group_label"]].itertuples(index=False)
    group_records = list(group_records)

    for i_scene, row in enumerate(used.sort_values(["date", "scene"]).itertuples(index=False), start=1):
        t_scene = time.time()
        scene = str(row.scene)
        log(f"[E {i_scene}/{len(used)}] Processing cached scene {scene}")
        clear_arr, clear_profile = read_uint8_mask(require_cache_file(Path(row.clear_mask_path)))
        if not same_grid(clear_profile, group_profile):
            raise RuntimeError(f"Clear mask grid does not match stable support group raster for {scene}")
        idx, idx_profile = read_float32_stack(require_cache_file(Path(row.index_stack_path)), expected_names=INDEX_STACK_BANDS)
        if not same_grid(idx_profile, group_profile):
            raise RuntimeError(f"Index stack grid does not match stable support group raster for {scene}")

        clear_mask = clear_arr == 1
        valid_mask = clear_mask & support_domain
        scene_rows: List[dict] = []
        for group_id, group_code, group_label in group_records:
            group_mask = valid_mask & (group_raster == int(group_id))
            if int(group_mask.sum()) < MIN_PIXELS_PER_GROUP_DATE:
                continue
            for index_name in USE_INDICES:
                arr = idx[index_name]
                vals = arr[group_mask]
                vals = vals[np.isfinite(vals)]
                if vals.size < MIN_PIXELS_PER_GROUP_DATE:
                    continue
                scene_rows.append({
                    "zip_file": scene,
                    "date": str(row.date),
                    "year": int(row.year),
                    "month": int(row.month),
                    "day": int(row.day),
                    "doy": int(row.doy),
                    "doy_bin_label": str(row.doy_bin_label),
                    "doy_bin_center": int(row.doy_bin_center),
                    "group_id": int(group_id),
                    "group_code": group_code,
                    "group_label": group_label,
                    "index": index_name,
                    "n_valid_pixels": int(vals.size),
                    "date_min": float(np.min(vals)),
                    "date_q10": float(np.quantile(vals, 0.10)),
                    "date_median": float(np.median(vals)),
                    "date_q90": float(np.quantile(vals, 0.90)),
                    "date_max": float(np.max(vals)),
                    "date_mean": float(np.mean(vals)),
                })
        if scene_rows:
            date_rows.extend(scene_rows)
            if WRITE_INTERMEDIATE:
                pd.DataFrame(scene_rows).to_csv(
                    intermediate_path,
                    mode="a",
                    header=not intermediate_path.exists(),
                    index=False,
                )
        log(f"[E {i_scene}/{len(used)}] Finished {scene} in {time.time() - t_scene:.1f}s; cumulative rows = {len(date_rows)}")

    if not date_rows:
        raise RuntimeError("No date-level group summaries could be computed from cache.")

    date_df = pd.DataFrame(date_rows).sort_values(["group_code", "index", "date", "zip_file"]).reset_index(drop=True)
    date_df.to_csv(OUTPUT_DIR / "date_group_index_medians.csv", index=False)

    date_df_for_env = collapse_duplicate_date_rows(date_df)
    date_df_for_env.to_csv(OUTPUT_DIR / "date_group_index_medians_by_unique_date.csv", index=False)

    env_rows = []
    group_cols = ["group_code", "group_label", "index", "doy_bin_label", "doy_bin_center"]
    for keys, sub in date_df_for_env.groupby(group_cols, dropna=False):
        group_code, group_label, index_name, bin_label, bin_center = keys
        medians = sub["date_median"].to_numpy(dtype=float)
        q10s = sub["date_q10"].to_numpy(dtype=float)
        q90s = sub["date_q90"].to_numpy(dtype=float)
        mins = sub["date_min"].to_numpy(dtype=float)
        maxs = sub["date_max"].to_numpy(dtype=float)
        n_unique_dates = int(sub["date"].nunique())
        n_scene_records = int(sub.get("n_scene_records", pd.Series([1] * len(sub), index=sub.index)).sum())
        support_pixels_total = int(sub["n_valid_pixels"].sum())
        support_pixels_per_date_min = int(sub["n_valid_pixels"].min())
        support_pixels_per_date_mean = float(sub["n_valid_pixels"].mean())
        env_q_low = float(np.quantile(medians, ENV_Q_LOW))
        env_q_med = float(np.quantile(medians, 0.50))
        env_q_high = float(np.quantile(medians, ENV_Q_HIGH))
        median_of_date_q10 = float(np.median(q10s))
        median_of_date_q90 = float(np.median(q90s))
        confidence_code = envelope_confidence_code(n_unique_dates, support_pixels_total)

        env_rows.append({
            "group_code": group_code,
            "group_label": group_label,
            "index": index_name,
            "doy_bin_label": bin_label,
            "doy_bin_center": int(bin_center),
            "n_dates": n_unique_dates,
            "n_unique_dates": n_unique_dates,
            "n_scene_records": n_scene_records,
            "support_pixels_total": support_pixels_total,
            "support_pixels_per_date_min": support_pixels_per_date_min,
            "support_pixels_per_date_mean": support_pixels_per_date_mean,
            "env_q_low": env_q_low,
            "env_q_med": env_q_med,
            "env_q_high": env_q_high,
            "env_q_width": float(env_q_high - env_q_low),
            "curve_min": float(np.min(medians)),
            "curve_med": float(np.median(medians)),
            "curve_max": float(np.max(medians)),
            "median_of_date_q10": median_of_date_q10,
            "median_of_date_q90": median_of_date_q90,
            "operational_width": float(median_of_date_q90 - median_of_date_q10),
            "min_of_date_min": float(np.min(mins)),
            "max_of_date_max": float(np.max(maxs)),
            "envelope_confidence": envelope_confidence_label(confidence_code),
            "envelope_confidence_code": confidence_code,
            "low_support_flag": bool(confidence_code < 2),
            "low_temporal_support_flag": bool(n_unique_dates < ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES),
            "support_pixels_total_low_flag": bool(support_pixels_total < MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE),
        })
    env_df = pd.DataFrame(env_rows).sort_values(["group_code", "index", "doy_bin_center"]).reset_index(drop=True)
    env_df.to_csv(OUTPUT_DIR / "doy_bin_envelopes.csv", index=False)
    write_envelope_quality_tables(env_df)

    s1_env_df = write_s1_descriptor_envelopes(group_raster, group_profile, stable_lut)

    coverage_df = (
        date_df_for_env.groupby(["group_code", "index"])
        .agg(
            n_dates=("date", "nunique"),
            n_scene_records=("n_scene_records", "sum"),
            min_doy=("doy", "min"),
            max_doy=("doy", "max"),
        )
        .reset_index()
        .sort_values(["group_code", "index"])
    )
    coverage_df.to_csv(OUTPUT_DIR / "group_index_date_coverage.csv", index=False)

    # Support summary: copy cache rule summary and append Algorithm #1 filtering details.
    if (CACHE_ROOT / "support_rule_summary.csv").exists():
        support_summary = pd.read_csv(CACHE_ROOT / "support_rule_summary.csv")
    else:
        support_summary = pd.DataFrame([{}])
    support_summary = support_summary.copy()
    support_summary["scene_filter_mode"] = SCENE_FILTER_MODE
    support_summary["zip_count_used"] = len(used)
    support_summary["unique_dates_used_for_envelopes"] = int(date_df_for_env["date"].nunique())
    support_summary["phase4_confidence_high_min_unique_dates"] = ENVELOPE_CONFIDENCE_HIGH_MIN_UNIQUE_DATES
    support_summary["phase4_confidence_medium_min_unique_dates"] = ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES
    support_summary["phase4_min_support_pixels_total_for_medium_confidence"] = MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE
    support_summary["n_low_confidence_envelope_rows"] = int((env_df["envelope_confidence_code"] < 2).sum())
    support_summary["phase3_cache_root"] = str(CACHE_ROOT)
    support_summary["phase5_s1_cache_root"] = str(S1_CACHE_ROOT)
    support_summary["phase5_s1_descriptor_envelopes_enabled"] = INCLUDE_S1_DESCRIPTOR_ENVELOPES
    support_summary["phase5_s1_envelope_rows"] = int(len(s1_env_df)) if "s1_env_df" in locals() else 0
    support_summary.to_csv(OUTPUT_DIR / "support_rule_summary.csv", index=False)

    emit_group_code_checks_cache(stable_lut, env_df)
    plot_date_source = PLOT_DATE_SOURCE.lower().strip()
    if plot_date_source == "scene_records":
        date_df_for_plot = date_df
    elif plot_date_source == "unique_date":
        date_df_for_plot = date_df_for_env
    else:
        raise ValueError("PLOT_DATE_SOURCE must be either 'unique_date' or 'scene_records'")
    write_optional_plots(env_df, date_df_for_plot)

    readme = OUTPUT_DIR / "README.txt"
    readme.write_text(
        "Algorithm #1 Phase 5 empirical optical envelopes and optional Sentinel-1 descriptor envelopes from shared caches.\n\n"
        f"Cache root: {CACHE_ROOT}\n"
        f"Cache manifest zip count: {manifest.get('zip_count')}\n"
        f"Scene filter mode: {SCENE_FILTER_MODE}\n"
        f"Scenes used for envelope rows: {len(used)}\n"
        f"Unique dates used for envelopes: {int(date_df_for_env['date'].nunique())}\n"
        f"Spectral indices: {', '.join(USE_INDICES)}\n"
        f"Sentinel-1 descriptor envelopes enabled: {INCLUDE_S1_DESCRIPTOR_ENVELOPES}\n"
        f"Sentinel-1 cache root: {S1_CACHE_ROOT}\n"
        f"Sentinel-1 descriptors for envelopes: {S1_DESCRIPTOR_BANDS_FOR_ENVELOPES}\n"
        f"DOY bin width: {DOY_BIN_WIDTH}\n"
        f"Envelope quantiles: {ENV_Q_LOW}, {ENV_Q_HIGH}\n"
        f"Plots enabled: {MAKE_PLOTS}\n"
        f"Plot date source: {PLOT_DATE_SOURCE}\n"
        f"Plot points colored by year: {COLOR_POINTS_BY_YEAR}\n"
        f"Plot points connected within year: {CONNECT_POINTS_WITHIN_YEAR}\n"
        f"Plot curve min/max: {SHOW_CURVE_MIN_MAX}\n"
        f"Plot operational q10/q90 bounds: {SHOW_OPERATIONAL_Q10_Q90}\n"
        f"Plot pixel min/max bounds: {SHOW_PIXEL_MIN_MAX_RANGE}\n"
        f"Plot low-confidence DOY-bin markers: {SHOW_LOW_CONFIDENCE_BIN_MARKERS}\n"
        f"Envelope confidence thresholds: high >= {ENVELOPE_CONFIDENCE_HIGH_MIN_UNIQUE_DATES} unique dates; medium >= {ENVELOPE_CONFIDENCE_MEDIUM_MIN_UNIQUE_DATES}; minimum support pixels for medium = {MIN_SUPPORT_PIXELS_TOTAL_FOR_MEDIUM_CONFIDENCE}\n"
        "Operational bounds later used by Algorithm #2: median_of_date_q10 and median_of_date_q90.\n"
        "Phase 4 confidence fields are diagnostic; they do not alter the envelope values.\n",
        encoding="utf-8",
    )

    if WRITE_OUTPUT_ZIP:
        log(f"Creating envelope ZIP bundle: {OUTPUT_ZIP}")
        zip_output_directory(OUTPUT_DIR, OUTPUT_ZIP)
        log(f"Envelope ZIP bundle written: {OUTPUT_ZIP}")

    log(f"Done in {time.time() - t0:.1f}s. Outputs in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
